globalVariables(c(
  ".pred",
  ".pred_lower",
  ".importance",
  ".importance_lower",
  ".importances",
  "importance",
  "int_level",
  "interval",
  "model",
  "model.importance",
  "model.pred",
  "pred_level",
  "resid_add",
  "resid_oob",
  "resid_train",
  "role",
  "variable"
))
